# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U-3w9mxpvrNii7RnqBJdmwq4f0FyFTH6
"""

from random import choices
from collections import Counter

x = [0,1,2] 
prob = [0.88,0.08,0.04]
#1000 simulations
simlen = 5000

sample = choices(x,prob,k=simlen)

_count = Counter(sample)

num_good = _count[0]
num_minor = _count[1]
num_major = _count[2]

prob_good = num_good/simlen
prob_minor = num_minor/simlen
prob_major = num_major/simlen

prob_jimmy = prob_good
prob_sujatha = prob_good+prob_minor



#graph
import seaborn as sns
import matplotlib.pyplot as plt

x=["good","minor","major"]
y=[prob_good*100,prob_minor*100,prob_major*100]
sns.barplot(x,y)
plt.show()



print(sample)
print(_count)

print()
print("Following results are obtained from the simulation")
print("(i)Probability that Jimmy accepts the shirt: {}".format(prob_jimmy))
print("(ii)Probability that Sujatha will accept the shirt: {}".format(prob_sujatha))
print()
print("Following results are obtained theoretically")
print("(i) Probability that Jimmy accepts the shirt: {}: 0.88")
print("(ii) Probability that Sujatha will accept the shirt: 0.96")
print()
print("Following are the absolute errors in calculating probabilties")
print("(i) Absolute error in calculating probability that Jimmy accepts the shirt: {}".format(abs(prob_jimmy - 0.88)))
print("(i) Absolute error in calculating probability that Sujatha accepts the shirt: {}".format(abs(prob_sujatha - 0.96)))
print("As the errors are negligible, we conclude both sets of results are approximately same")



_